---
  - name: Update the inventory for the Ansible Deployment
    hosts: localhost
    connection: local
    gather_facts: no

    tasks:

    - name: Get an AAP API Token and store it as new_token
      register: new_token
      ansible.builtin.uri:
        url: "https://{{ controller_url }}/api/v2/tokens/"
        method: POST
        user: "{{ controller_user }}"
        password: "{{ controller_passwd }}"
        validate_certs: no
        force_basic_auth: yes
        status_code: 201
        return_content: yes       

    - name: Debug my_server_data
      ansible.builtin.debug:
        var: my_server_data
    
    - name: Update the AAP AWS Managed Inventory with the event drivers
      loop: "{{ my_server_data['results']['ansible_stats']['data']['my_event_driver_public_names'] }}"
      awx.awx.host:
        controller_host: "https://{{ controller_url }}"
        #controller_password: "{{ controller_passwd }}"
        controller_username: "{{ controller_user }}"
        controller_oauthtoken: "{{ new_token.json.token }}"
        name: "{{ item }}"
        inventory: "AAP AWS Inventory - Managed"
        state: present
        enabled: true