---
- name: Time to install and configure Ansible Automation Platform
  hosts: control
  gather_facts: no

  tasks:
       
    - name: Get the Ansible Bundle
      ansible.builtin.get_url:
        url: https://access.cdn.redhat.com/content/origin/files/sha256/95/95f5bfc00f65be7785098bf196f21e76c3eca54f95b203ba8655c80676f665a7/ansible-automation-platform-setup-bundle-2.4-1-x86_64.tar.gz
        dest: /root/ansible-automation-platform-setup-bundle-2.4-1-x86_64.tar.gz
        mode: '0755'
        validate_certs: no
        client_cert: /etc/pki/entitlement/4790000255323135399.pem
        client_key: /etc/pki/entitlement/4790000255323135399-key.pem

    - name: Untar and unzip the ansible bundle
      ansible.builtin.unarchive:
        src: /root/ansible-automation-platform-setup-bundle-2.4-1-x86_64.tar.gz
        dest: /root/
        remote_src: true