---
- name: Time to install and configure Ansible Automation Platform
  hosts: control
  gather_facts: no
  vars:
    aap_bundle_sha_value: 011a80be33c9b202e94f3a18e673e3d19eb1b2f480c49ef662205443576cfceb

  tasks:
       
    - name: Ensure we have a access token the Red Hat Customer portal
      register: access_token
      until: access_token is not failed
      retries: 1
      delay: 20
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type: "refresh_token"
          client_id: "rhsm-api"
          refresh_token: "{{ offline_token }}"

    - name: Ensure we have the AAP bundle
      register: download_aap_tarball
      until: download_aap_tarball is not failed
      retries: 15
      delay: 20
      ansible.builtin.get_url:
        url: "https://api.access.redhat.com/management/v1/images/{{ aap_bundle_sha_value }}/download"
        headers:
          accept: "application/json"
          Authorization: "Bearer {{ access_token.json.access_token }}"
        dest: /root/aap.tar.gz
        checksum: "sha256: {{ aap_bundle_sha_value }}"

    - name: Ensure the aap bundle is opened up
      ansible.builtin.unarchive:
        src: /root/aap.tar.gz
        dest: /root/
        remote_src: yes

    - name: Ensure we have a public/private ssh key
      register: ec2_user_controller_aws_pub_key
      become_user: ec2-user 
      community.crypto.openssh_keypair:
        path: /home/ec2-user/.ssh/id_rsa
        comment: ec2-user@controller.aws

    - name: print 
      debug:
        var: ec2_user_controller_aws_pub_key