---
- name: Time to install and configure Ansible Automation Platform
  hosts: localhost
  gather_facts: no

  tasks:
       
    - name: Get the Ansible Bundle
      ansible.builtin.get_url:
        url: https://access.cdn.redhat.com/content/origin/files/sha256/72/72cdff125cbfef9bdda28630a6897d8012a5df71009ee3143e94a34080907779/ansible-automation-platform-setup-2.4-1.tar.gz
        dest: /var/tmp/ansible-automation-platform-setup-bundle-2.4-1-x86_64.tar.gz
        mode: '0775'
        validate_certs: no
        client_cert: /etc/pki/entitlement/4790000255323135399.pem
        client_key: /etc/pki/entitlement/4790000255323135399-key.pem