---
- name: Time to install and configure Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
       
    - name: Get the Ansible Bundle
      ansible.builtin.get_url:
        url: https://access.cdn.redhat.com/content/origin/files/sha256/01/011a80be33c9b202e94f3a18e673e3d19eb1b2f480c49ef662205443576cfceb/ansible-automation-platform-setup-bundle-2.4-1.1-x86_64.tar.gz
        dest: /var/tmp/ansible-automation-platform-setup-bundle-2.4-1.1-x86_64.tar.gz
        mode: '0775'
        validate_certs: no
        client_cert: /etc/pki/entitlement/4790000255323135399.pem
        client_key: /etc/pki/entitlement/4790000255323135399-key.pem