---
- name: Time to install and configure Ansible Automation Platform
  hosts: control
  gather_facts: no
  vars:
    aap_bundle_sha_value: 011a80be33c9b202e94f3a18e673e3d19eb1b2f480c49ef662205443576cfceb

  tasks:
       
    - name: Ensure we have a access token
      register: access_token
      until: access_token is not failed
      retries: 1
      delay: 20
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type: "refresh_token"
          client_id: "rhsm-api"
          refresh_token: "{{ offline_token }}"

    - name: print shit 
      debug:
        var: access_token