---
- name: Ensure we update the known_host file on the controllers
  hosts: all
  gather_facts: false

  tasks:

    - name: Ensure the Controller is in the file
      when: "'control' in group_names"
      loop: "{{ query('inventory_hostnames', 'all') }}"
      ansible.builtin.shell: /usr/bin/ssh -o "StrictHostKeyChecking no" {{ item }} date