---
  - name: Gather AAP AWS Controller info
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       region: ''
       servername: ''

    tasks:

    - name: Get instances id with tag {{ servername }} in {{ region }}
      register: instance_info
      until: instance_info.instances[0].instance_id is defined
      retries: 5
      delay: 10
      amazon.aws.ec2_instance_info:
       region: "{{ region }}"
       filters:
         "tag:Name": "{{ servername }}"
         instance-state-name: [ "running"]
         "tag:Contact": "{{ my_email_address }}"

    - name: Capture public dns name
      register: my_aws_controller
      ansible.builtin.set_stats:
        data:
          my_aws_controller: "{{ instance_info.instances[0].public_dns_name }}"

    - name: Capture public ip address
      register: my_aws_controller_public_ip
      ansible.builtin.set_stats:
        data:
          my_aws_controller_public_ip: "{{ instance_info.instances[0].public_ip_address }}"