---
- name: Ensure the AAP Inventory file is up to date prior to running setup
  hosts: control
  gather_facts: false

  tasks:

    - name: Ensure we have the AAP bundle directory
      register: aap_bundle_dir
      changed_when: false
      ansible.builtin.shell: ls -d /root/ansible-automation-platform-setup-bundle*

    - name: Ensure the Controller is in the file
      loop: "{{ my_controller_server_data['instances'] }}"
      ansible.builtin.lineinfile:
        path: "{{ aap_bundle_dir.stdout }}/inventory"
        insertafter: '^.automationcontroller.$'
        line: "{{ item['public_dns_name'] }}"
        state: present

    - name: Ensure the EDA Server is in the file
      loop: "{{ my_eda_server_data['instances'] }}"
      ansible.builtin.lineinfile:
        path: "{{ aap_bundle_dir.stdout }}/inventory"
        insertafter: '^.automationedacontroller.$'
        line: "{{ item['public_dns_name'] }}"
        state: present

    - name: Ensure we are ready for our password
      loop:
        - "admin_password"
        - "pg_password"
        - "automationhub_admin_password"
        - "automationhub_pg_password"
        - "automationedacontroller_admin_password"
        - "automationedacontroller_pg_password"
      ansible.builtin.lineinfile:
        path: "{{ aap_bundle_dir.stdout }}/inventory"
        regexp: "{{ item }}=''"
        line: "{{ item }}=''\\{{ PASSWORDGOESHERE }}''"