---
- name: Ensure the AAP Inventory file is up to date prior to running setup
  hosts: control
  gather_facts: false

  tasks:

    - name: Ensure we have the AAP bundle directory
      register: aap_bundle_dir
      changed_when: false
      ansible.builtin.shell: ls -d /root/ansible-automation-platform-setup-bundle*

    - name: Ensure the Controller is in the file
      ansible.builtin.lineinfile:
        path: "{{ aap_bundle_dir.stdout }}/inventory"
        regexp: '^[automationcontroller]'
        insertafter: '^[automationcontroller]'
        line: "{{ my_controller_server_data['public_dns_name'] }}"

    - name: Ensure the EDA Server is in the file
      ansible.builtin.lineinfile:
        path: "{{ aap_bundle_dir.stdout }}/inventory"
        regexp: '^[automationedacontroller]'
        insertafter: '^[automationedacontroller]'
        line: "{{ my_eda_server_data['public_dns_name'] }}"
    
    - name: Ensure admin_password is variablelized
      ansible.builtin.lineinfile:
        path: "{{ aap_bundle_dir.stdout }}/inventory"
        regexp: '^admin_password='''
        line: "admin_password='{{ my_admin_password }}'"